// Bilingual situation prompt bank for KAO // 顔.
export interface Situation {
  en: string;
  ru: string;
}
export const SITUATIONS: Situation[] = [
  { en: "When the WiFi drops mid-ranked game", ru: "Когда вайфай отвалился прямо посреди катки" },
  { en: "POV: your post gets one like and it's your mom", ru: "POV: под постом один лайк, и тот от мамы" },
  { en: "When you accidentally like a photo from 2014", ru: "Когда случайно лайкнул фотку из 2014 года" },
  { en: "That moment when the algorithm reads your mind", ru: "Тот момент, когда алгоритм будто читает твои мысли" },
  { en: "When someone replies \"k\" to your essay", ru: "Когда на твою простыню текста отвечают «ок»" },
  { en: "Your face when the group sees your screen time", ru: "Твоё лицо, когда все увидели твоё экранное время" },
  { en: "When a stranger quote-tweets you into oblivion", ru: "Когда незнакомец разнёс тебя цитатой на весь интернет" },
  { en: "POV: you went viral for the wrong reason", ru: "POV: ты завирусился, но совсем не за то" },
  { en: "When the comments section turns on you", ru: "Когда комментарии ополчились против тебя" },
  { en: "When you finally get the joke a week later", ru: "Когда дошла шутка только через неделю" },
  { en: "When your throwaway take gets 40k likes", ru: "Когда твой случайный коммент собрал 40 тысяч лайков" },
  { en: "When the influencer says \"it's free, just pay shipping\"", ru: "Когда блогер говорит «это бесплатно, только за доставку заплати»" },
  { en: "When you doomscroll until the sun comes up", ru: "Когда залип в ленту до самого рассвета" },
  { en: "When the app updates and ruins everything", ru: "Когда приложение обновилось и всё испортило" },
  { en: "When you read \"see more\" and immediately regret it", ru: "Когда нажал «показать ещё» и сразу пожалел" },
  { en: "When your teammate runs in 1v5 and pings you", ru: "Когда тиммейт полез один на пятерых и ещё пингует тебя" },
  { en: "POV: you're the last one alive and lagging", ru: "POV: ты остался последний в живых, и тут лаги" },
  { en: "When the kill cam shows they were aimbotting", ru: "Когда килл-кам показал, что у него был аимбот" },
  { en: "When you finally hit the rank you wanted", ru: "Когда наконец залутал желанный ранг" },
  { en: "When the server says \"queue: 38 minutes\"", ru: "Когда сервер пишет «очередь: 38 минут»" },
  { en: "When friendly fire was very much on purpose", ru: "Когда тиммейта подстрелил абсолютно специально" },
  { en: "When the boss has a second health bar", ru: "Когда у босса оказалась вторая полоска хп" },
  { en: "When someone leaves ranked at the worst moment", ru: "Когда кто-то вышел из рейтинга в самый неподходящий момент" },
  { en: "When the loot is everything but what you needed", ru: "Когда выпало всё что угодно, кроме того, что нужно" },
  { en: "When you fall off the map for no reason", ru: "Когда упал за карту вообще без причины" },
  { en: "That moment when your controller disconnects mid-clutch", ru: "Тот момент, когда геймпад отрубился на решающем моменте" },
  { en: "When the noob carries the whole lobby", ru: "Когда нуб вытащил всю катку на себе" },
  { en: "When you're left on read for three days", ru: "Когда тебя продержали в прочитанных три дня" },
  { en: "When someone @everyone for absolutely nothing", ru: "Когда кто-то тегнул @все вообще ни по какому поводу" },
  { en: "POV: you sent the message to the wrong chat", ru: "POV: отправил сообщение не в тот чат" },
  { en: "When the typing bubble appears and then vanishes", ru: "Когда появилось «печатает...» и тут же пропало" },
  { en: "When the family group chat finds a new meme", ru: "Когда семейный чат открыл для себя новый мем" },
  { en: "When you double-text and they finally reply \"haha\"", ru: "Когда написал два раза подряд, а тебе наконец «ахаха»" },
  { en: "When 200 unread messages appear overnight", ru: "Когда за ночь накопилось 200 непрочитанных" },
  { en: "When autocorrect makes it so much worse", ru: "Когда автозамена сделала только хуже" },
  { en: "When someone screenshots your message into another chat", ru: "Когда твой скрин слили в другой чат" },
  { en: "When the plan dies in the group chat as usual", ru: "Когда план как обычно умер в общем чате" },
  { en: "When you reply-all by accident", ru: "Когда случайно ответил всем разом" },
  { en: "When the meeting could have been an email", ru: "Когда созвон спокойно мог быть письмом" },
  { en: "POV: you unmute and everyone is staring", ru: "POV: включил микрофон, а все молча смотрят на тебя" },
  { en: "When \"per my last email\" enters the chat", ru: "Когда в чат влетает «как я писал ранее»" },
  { en: "When your boss says \"quick question\" at 4:59 pm", ru: "Когда босс в 18:59 пишет «короткий вопросик»" },
  { en: "When the screen share shows your messy desktop", ru: "Когда при демонстрации экрана все увидели твой бардак на рабочем столе" },
  { en: "When you're still talking and your mic was off", ru: "Когда ты вещаешь, а микрофон всё это время был выключен" },
  { en: "When the calendar invite says \"recurring\"", ru: "Когда в приглашении стоит «повторяется еженедельно»" },
  { en: "When someone schedules a meeting to plan a meeting", ru: "Когда назначили встречу, чтобы спланировать встречу" },
  { en: "When you get \"as discussed\" and you don't remember", ru: "Когда тебе пишут «как договаривались», а ты не помнишь" },
  { en: "When the printer jams during the big presentation", ru: "Когда принтер зажевал бумагу прямо перед важной презентацией" },
  { en: "When payroll is one day late", ru: "Когда зарплату задержали всего на один день" },
  { en: "When you say \"you too\" to the wrong thing", ru: "Когда сказал «и вам того же» совсем невпопад" },
  { en: "When the teacher says \"this will be on the test\"", ru: "Когда учитель говорит «это будет на контрольной»" },
  { en: "When the group project is just you", ru: "Когда групповой проект — это только ты один" },
  { en: "POV: the exam is nothing like the study guide", ru: "POV: экзамен вообще не такой, как в методичке" },
  { en: "When you raise your hand and forget the answer", ru: "Когда поднял руку и тут же забыл ответ" },
  { en: "When the deadline got moved to tonight", ru: "Когда дедлайн внезапно перенесли на сегодня вечером" },
  { en: "When you find the homework was due yesterday", ru: "Когда выяснилось, что домашку надо было сдать вчера" },
  { en: "When the substitute has your real schedule", ru: "Когда у заменяющего препода оказалось твоё настоящее расписание" },
  { en: "When you sit in the wrong classroom for ten minutes", ru: "Когда десять минут сидел не в той аудитории" },
  { en: "When everyone laughed and you don't know why", ru: "Когда все засмеялись, а ты не понял почему" },
  { en: "When they say \"we need to talk\"", ru: "Когда тебе говорят «нам нужно поговорить»" },
  { en: "POV: the date used a five-year-old photo", ru: "POV: на свидании человек оказался с фото пятилетней давности" },
  { en: "When you triple-text and then see them online", ru: "Когда написал три раза подряд и тут видишь, что человек онлайн" },
  { en: "When your crush likes someone else's selfie", ru: "Когда твой краш лайкнул чужое селфи" },
  { en: "When the first date goes too well to be real", ru: "Когда первое свидание прошло подозрительно идеально" },
  { en: "When they suggest splitting the bill exactly", ru: "Когда предлагают разделить счёт ровно до копейки" },
  { en: "When you wave back at someone waving past you", ru: "Когда помахал в ответ, а махали вообще не тебе" },
  { en: "When the ex shows up everywhere now", ru: "Когда бывший теперь попадается буквально везде" },
  { en: "When they reply with a thumbs up only", ru: "Когда тебе отвечают одним лишь большим пальцем" },
  { en: "When mom finds your search history", ru: "Когда мама нашла историю твоих поисков" },
  { en: "When dad tells the same story at dinner again", ru: "Когда папа за ужином снова рассказывает ту же историю" },
  { en: "POV: relatives ask about your love life", ru: "POV: родственники опять спрашивают про личную жизнь" },
  { en: "When grandma comments on every single photo", ru: "Когда бабушка комментирует абсолютно каждую фотку" },
  { en: "When the parents ask to \"see your phone\"", ru: "Когда родители просят «дай-ка глянуть твой телефон»" },
  { en: "When you're the family tech support again", ru: "Когда ты снова за весь дом техподдержка" },
  { en: "When your sibling rats you out instantly", ru: "Когда брат или сестра сдаёт тебя с потрохами за секунду" },
  { en: "When mom says \"we'll talk when we get home\"", ru: "Когда мама говорит «дома поговорим»" },
  { en: "When the whole family naps after lunch", ru: "Когда вся семья после обеда дружно ушла в сон" },
  { en: "When the delivery driver eats one fry", ru: "Когда курьер сожрал одну твою картошку фри" },
  { en: "POV: you bite into the spicy one by mistake", ru: "POV: случайно откусил самый острый кусок" },
  { en: "When the restaurant is out of the one thing you wanted", ru: "Когда в кафе закончилось ровно то единственное, что ты хотел" },
  { en: "When you reheat pizza and it's somehow perfect", ru: "Когда разогрел вчерашнюю пиццу, а она почему-то идеальна" },
  { en: "When the milk smells suspicious", ru: "Когда молоко как-то подозрительно пахнет" },
  { en: "When you order a salad and regret it instantly", ru: "Когда заказал салат и сразу же пожалел" },
  { en: "When the snack is more air than chips", ru: "Когда в пачке чипсов больше воздуха, чем чипсов" },
  { en: "When you find leftovers you forgot about", ru: "Когда нашёл в холодильнике еду, про которую забыл" },
  { en: "When someone takes the last slice", ru: "Когда кто-то забрал последний кусок" },
  { en: "When the new recipe is a complete disaster", ru: "Когда новый рецепт обернулся полной катастрофой" },
  { en: "When the bank app shows the wrong direction", ru: "Когда в банковском приложении цифра поехала не в ту сторону" },
  { en: "POV: a \"free trial\" just charged you", ru: "POV: «бесплатный пробный период» только что списал деньги" },
  { en: "When the receipt is longer than your arm", ru: "Когда чек длиннее твоей руки" },
  { en: "When you find $20 in an old coat", ru: "Когда нашёл тысячу рублей в старой куртке" },
  { en: "When the subscription you forgot keeps renewing", ru: "Когда забытая подписка всё списывает и списывает" },
  { en: "When rent is due and so is everything else", ru: "Когда подошла аренда, а вместе с ней и всё остальное" },
  { en: "When the ATM eats your card", ru: "Когда банкомат проглотил твою карту" },
  { en: "When \"treat yourself\" becomes the whole paycheck", ru: "Когда «балуй себя» внезапно стало всей зарплатой" },
  { en: "When the price doubled since last week", ru: "Когда цена выросла вдвое всего за неделю" },
  { en: "When you trip in front of the entire bus stop", ru: "Когда споткнулся на глазах у всей остановки" },
  { en: "POV: you wave at a stranger you mistook for a friend", ru: "POV: машешь незнакомцу, приняв его за друга" },
  { en: "When your stomach growls in total silence", ru: "Когда живот заурчал в гробовой тишине" },
  { en: "When you push a pull door with confidence", ru: "Когда уверенно толкнул дверь, на которой «на себя»" },
  { en: "When you laugh at a joke you didn't hear", ru: "Когда смеёшься над шуткой, которую не расслышал" },
  { en: "When you walk into the glass door", ru: "Когда впечатался лицом в стеклянную дверь" },
  { en: "When your name is called wrong at graduation", ru: "Когда на выпускном твоё имя объявили неправильно" },
  { en: "When you clap at the wrong moment", ru: "Когда захлопал не в тот момент" },
  { en: "When you say \"happy birthday\" to the wrong person", ru: "Когда поздравил с днём рождения не того человека" },
  { en: "When the screen freezes right before you save", ru: "Когда экран завис ровно перед сохранением" },
  { en: "POV: it was working five minutes ago", ru: "POV: пять минут назад всё работало" },
  { en: "When the update bricks the whole device", ru: "Когда обновление превратило устройство в кирпич" },
  { en: "When you have 1% battery and no charger", ru: "Когда 1% зарядки и ни одной розетки рядом" },
  { en: "When the loading bar hits 99% and stops", ru: "Когда загрузка дошла до 99% и замерла" },
  { en: "When \"have you tried turning it off and on\" works", ru: "Когда «а ты выключи и включи» реально помогло" },
  { en: "When the cloud loses the file you needed", ru: "Когда облако потеряло именно тот файл, что был нужен" },
  { en: "When the smart home refuses to be smart", ru: "Когда умный дом наотрез отказывается быть умным" },
  { en: "When the cable was unplugged the whole time", ru: "Когда оказалось, что провод всё это время был выдернут" },
  { en: "When the printer is \"out of cyan\" again", ru: "Когда принтер опять пишет «закончился голубой»" },
  { en: "When you remember something cringe from 2009", ru: "Когда вспомнил кринж из 2009 года" },
  { en: "POV: it's 3 am and your brain wants to talk", ru: "POV: три часа ночи, а мозг настроен поболтать" },
  { en: "When you realize it's already June somehow", ru: "Когда осознал, что уже как-то июнь" },
  { en: "When the existential dread arrives on schedule", ru: "Когда экзистенциальная тоска приходит точно по расписанию" },
  { en: "When you stare into the fridge for the fifth time", ru: "Когда пятый раз залипаешь в холодильник" },
  { en: "When you can't remember why you walked in here", ru: "Когда зашёл в комнату и забыл зачем" },
  { en: "When the Sunday scaries hit at noon", ru: "Когда воскресная тоска накрыла уже в обед" },
  { en: "When you finish the series and feel empty", ru: "Когда досмотрел сериал и внутри пустота" },
  { en: "When you wonder if the cashier is doing okay", ru: "Когда задумался, а нормально ли там у кассира на душе" },
  { en: "When the to-do list judges you silently", ru: "Когда список дел молча тебя осуждает" },
  { en: "When the forecast lied and now you're soaked", ru: "Когда прогноз наврал, и ты теперь промок до нитки" },
  { en: "POV: it's snowing in what should be spring", ru: "POV: на дворе вроде весна, а валит снег" },
  { en: "When the AC dies on the hottest day", ru: "Когда кондиционер сдох в самый жаркий день" },
  { en: "When the first cold morning arrives uninvited", ru: "Когда первое холодное утро нагрянуло без приглашения" },
  { en: "When the umbrella flips inside out", ru: "Когда зонт вывернуло наизнанку" },
  { en: "When you finally see the sun after a week of rain", ru: "Когда наконец увидел солнце после недели дождей" },
  { en: "When the heat wave makes the sidewalk sticky", ru: "Когда от жары асфальт буквально плавится под ногами" },
  { en: "When leaves fall and so does your motivation", ru: "Когда листья опадают, а с ними и вся мотивация" },
  { en: "When the toast lands butter-side down, again", ru: "Когда бутерброд снова упал маслом вниз" },
  { en: "POV: a pigeon makes intense eye contact with you", ru: "POV: голубь смотрит тебе прямо в душу" },
  { en: "When the elevator stops at every single floor", ru: "Когда лифт останавливается на каждом этаже" },
  { en: "When you find a door where a wall used to be", ru: "Когда нашёл дверь там, где раньше была стена" },
  { en: "When the clock reads a time that doesn't exist", ru: "Когда часы показывают время, которого не бывает" },
  { en: "When your shadow does something you didn't", ru: "Когда твоя тень сделала то, чего ты не делал" },
  { en: "When the vending machine gives you two for free", ru: "Когда автомат выдал тебе две банки вместо одной" },
  { en: "When a balloon follows you down the street", ru: "Когда воздушный шарик увязался за тобой по улице" },
  { en: "When the cat stares at the corner for an hour", ru: "Когда кот час пялится в пустой угол" },
  { en: "When the GPS says \"you have arrived\" in a field", ru: "Когда навигатор сказал «вы прибыли» посреди поля" },
  { en: "When you wake up convinced it's a different year", ru: "Когда проснулся в полной уверенности, что на дворе другой год" },
  { en: "When the mannequin definitely just moved", ru: "Когда манекен совершенно точно только что шевельнулся" },
  { en: "When the karaoke key is way too high", ru: "Когда в караоке тональность оказалась слишком высокой" },
  { en: "POV: the dentist says \"you've been flossing, right?\"", ru: "POV: стоматолог спрашивает «ниткой-то пользуетесь, да?»" },
  { en: "When the gym playlist is unexpectedly perfect", ru: "Когда плейлист в зале неожиданно зашёл идеально" },
  { en: "When the alarm didn't go off but you woke up anyway", ru: "Когда будильник не сработал, но ты всё равно проснулся" },
  { en: "When the line moves and you're somehow further back", ru: "Когда очередь двинулась, а ты почему-то оказался ещё дальше" },
  { en: "When the joke landed exactly as planned", ru: "Когда шутка зашла ровно так, как ты задумал" },
  { en: "When you nail the parallel park with an audience", ru: "Когда идеально припарковался задним ходом на глазах у зрителей" },
  { en: "When the package says \"delivered\" but it isn't", ru: "Когда посылка «доставлена», но её нигде нет" },
  { en: "When the meeting ends ten minutes early", ru: "Когда созвон закончился на десять минут раньше" },
  { en: "When you find the perfect parking spot taken", ru: "Когда идеальное место для парковки уже занято" },
  { en: "When the new haircut is not what you asked for", ru: "Когда новая стрижка совсем не то, о чём ты просил" },
  { en: "When the elevator door opens to the wrong floor", ru: "Когда двери лифта открылись не на том этаже" },
  { en: "When you remember you left the stove on", ru: "Когда вспомнил, что оставил плиту включённой" },
  { en: "When the coffee shop spells your name beautifully wrong", ru: "Когда в кофейне твоё имя написали красиво, но неправильно" },
  { en: "When the playlist shuffles to your ex's song", ru: "Когда в случайном порядке заиграла песня вашей с бывшим темы" },
  { en: "When you finally beat the level you were stuck on", ru: "Когда наконец прошёл уровень, на котором застрял навечно" },
  { en: "When the spreadsheet formula finally works", ru: "Когда формула в таблице наконец-то заработала" },
  { en: "When the cat knocks the cup off on purpose", ru: "Когда кот демонстративно скинул чашку со стола" },
  { en: "When the recruiter says \"we went another direction\"", ru: "Когда рекрутер пишет «мы выбрали другого кандидата»" },
  { en: "When the headphones snag and yank out of your ears", ru: "Когда наушники зацепились и выдернулись прямо из ушей" },
];
