// Situation prompt bank for KAO // 顔.
// Each entry is a short, evocative scenario the player reacts to with a face.
export const SITUATIONS: string[] = [
  // internet / social-media culture
  "When the WiFi drops mid-ranked game",
  "POV: your post gets one like and it's your mom",
  "When you accidentally like a photo from 2014",
  "That moment when the algorithm reads your mind",
  "When someone replies \"k\" to your essay",
  "Your face when the group sees your screen time",
  "When a stranger quote-tweets you into oblivion",
  "POV: you went viral for the wrong reason",
  "When the comments section turns on you",
  "When you finally get the joke a week later",
  "When your throwaway take gets 40k likes",
  "When the influencer says \"it's free, just pay shipping\"",
  "When you doomscroll until the sun comes up",
  "When the app updates and ruins everything",
  "When you read \"see more\" and immediately regret it",

  // online gaming
  "When your teammate runs in 1v5 and pings you",
  "POV: you're the last one alive and lagging",
  "When the kill cam shows they were aimbotting",
  "When you finally hit the rank you wanted",
  "When the server says \"queue: 38 minutes\"",
  "When friendly fire was very much on purpose",
  "When the boss has a second health bar",
  "When someone leaves ranked at the worst moment",
  "When the loot is everything but what you needed",
  "When you fall off the map for no reason",
  "That moment when your controller disconnects mid-clutch",
  "When the noob carries the whole lobby",

  // group chats & texting
  "When you're left on read for three days",
  "When someone @everyone for absolutely nothing",
  "POV: you sent the message to the wrong chat",
  "When the typing bubble appears and then vanishes",
  "When the family group chat finds a new meme",
  "When you double-text and they finally reply \"haha\"",
  "When 200 unread messages appear overnight",
  "When autocorrect makes it so much worse",
  "When someone screenshots your message into another chat",
  "When the plan dies in the group chat as usual",
  "When you reply-all by accident",

  // work / meetings / email
  "When the meeting could have been an email",
  "POV: you unmute and everyone is staring",
  "When \"per my last email\" enters the chat",
  "When your boss says \"quick question\" at 4:59 pm",
  "When the screen share shows your messy desktop",
  "When you're still talking and your mic was off",
  "When the calendar invite says \"recurring\"",
  "When someone schedules a meeting to plan a meeting",
  "When you get \"as discussed\" and you don't remember",
  "When the printer jams during the big presentation",
  "When payroll is one day late",
  "When you say \"you too\" to the wrong thing",

  // school
  "When the teacher says \"this will be on the test\"",
  "When the group project is just you",
  "POV: the exam is nothing like the study guide",
  "When you raise your hand and forget the answer",
  "When the deadline got moved to tonight",
  "When you find the homework was due yesterday",
  "When the substitute has your real schedule",
  "When you sit in the wrong classroom for ten minutes",
  "When everyone laughed and you don't know why",

  // dating & relationships
  "When they say \"we need to talk\"",
  "POV: the date used a five-year-old photo",
  "When you triple-text and then see them online",
  "When your crush likes someone else's selfie",
  "When the first date goes too well to be real",
  "When they suggest splitting the bill exactly",
  "When you wave back at someone waving past you",
  "When the ex shows up everywhere now",
  "When they reply with a thumbs up only",

  // family & parents
  "When mom finds your search history",
  "When dad tells the same story at dinner again",
  "POV: relatives ask about your love life",
  "When grandma comments on every single photo",
  "When the parents ask to \"see your phone\"",
  "When you're the family tech support again",
  "When your sibling rats you out instantly",
  "When mom says \"we'll talk when we get home\"",
  "When the whole family naps after lunch",

  // food
  "When the delivery driver eats one fry",
  "POV: you bite into the spicy one by mistake",
  "When the restaurant is out of the one thing you wanted",
  "When you reheat pizza and it's somehow perfect",
  "When the milk smells suspicious",
  "When you order a salad and regret it instantly",
  "When the snack is more air than chips",
  "When you find leftovers you forgot about",
  "When someone takes the last slice",
  "When the new recipe is a complete disaster",

  // money
  "When the bank app shows the wrong direction",
  "POV: a \"free trial\" just charged you",
  "When the receipt is longer than your arm",
  "When you find $20 in an old coat",
  "When the subscription you forgot keeps renewing",
  "When rent is due and so is everything else",
  "When the ATM eats your card",
  "When \"treat yourself\" becomes the whole paycheck",
  "When the price doubled since last week",

  // public / social cringe
  "When you trip in front of the entire bus stop",
  "POV: you wave at a stranger you mistook for a friend",
  "When your stomach growls in total silence",
  "When you push a pull door with confidence",
  "When you laugh at a joke you didn't hear",
  "When you walk into the glass door",
  "When your name is called wrong at graduation",
  "When you clap at the wrong moment",
  "When you say \"happy birthday\" to the wrong person",

  // technology breaking
  "When the screen freezes right before you save",
  "POV: it was working five minutes ago",
  "When the update bricks the whole device",
  "When you have 1% battery and no charger",
  "When the loading bar hits 99% and stops",
  "When \"have you tried turning it off and on\" works",
  "When the cloud loses the file you needed",
  "When the smart home refuses to be smart",
  "When the cable was unplugged the whole time",
  "When the printer is \"out of cyan\" again",

  // existential / mood
  "When you remember something cringe from 2009",
  "POV: it's 3 am and your brain wants to talk",
  "When you realize it's already June somehow",
  "When the existential dread arrives on schedule",
  "When you stare into the fridge for the fifth time",
  "When you can't remember why you walked in here",
  "When the Sunday scaries hit at noon",
  "When you finish the series and feel empty",
  "When you wonder if the cashier is doing okay",
  "When the to-do list judges you silently",

  // weather / seasons
  "When the forecast lied and now you're soaked",
  "POV: it's snowing in what should be spring",
  "When the AC dies on the hottest day",
  "When the first cold morning arrives uninvited",
  "When the umbrella flips inside out",
  "When you finally see the sun after a week of rain",
  "When the heat wave makes the sidewalk sticky",
  "When leaves fall and so does your motivation",

  // pure absurd / surreal
  "When the toast lands butter-side down, again",
  "POV: a pigeon makes intense eye contact with you",
  "When the elevator stops at every single floor",
  "When you find a door where a wall used to be",
  "When the clock reads a time that doesn't exist",
  "When your shadow does something you didn't",
  "When the vending machine gives you two for free",
  "When a balloon follows you down the street",
  "When the cat stares at the corner for an hour",
  "When the GPS says \"you have arrived\" in a field",
  "When you wake up convinced it's a different year",
  "When the mannequin definitely just moved",

  // extra mix for spread
  "When the karaoke key is way too high",
  "POV: the dentist says \"you've been flossing, right?\"",
  "When the gym playlist is unexpectedly perfect",
  "When the alarm didn't go off but you woke up anyway",
  "When the line moves and you're somehow further back",
  "When the joke landed exactly as planned",
  "When you nail the parallel park with an audience",
  "When the package says \"delivered\" but it isn't",
  "When the meeting ends ten minutes early",
  "When you find the perfect parking spot taken",
  "When the new haircut is not what you asked for",
  "When the elevator door opens to the wrong floor",
  "When you remember you left the stove on",
  "When the coffee shop spells your name beautifully wrong",
  "When the playlist shuffles to your ex's song",
  "When you finally beat the level you were stuck on",
  "When the spreadsheet formula finally works",
  "When the cat knocks the cup off on purpose",
  "When the recruiter says \"we went another direction\"",
  "When the headphones snag and yank out of your ears",
];
